// Generated by CoffeeScript 1.3.1
(function() {
  var HOST, assetUrlsIn, fs, fullPath, manifest, timestamp, urls;

  fs = require('fs');

  HOST = 'http://angryponies.herokuapp.com';

  fullPath = function(path) {
    return __dirname + '/' + path;
  };

  assetUrlsIn = function(dir, format) {
    var filenames, name, urls;
    filenames = fs.readdirSync(fullPath('../' + dir));
    urls = (function() {
      var _i, _len, _results;
      _results = [];
      for (_i = 0, _len = filenames.length; _i < _len; _i++) {
        name = filenames[_i];
        if (name.match(format)) {
          _results.push(HOST + '/' + dir + '/' + name);
        }
      }
      return _results;
    })();
    return urls;
  };

  manifest = fs.readFileSync(fullPath('/manifest.tmpl'), 'utf8');

  timestamp = (new Date).getTime();

  manifest = manifest.replace("{MANIFEST_ID}", timestamp);

  urls = assetUrlsIn('images', /\.png$/);

  urls = urls.concat(assetUrlsIn('flash', /\.swf$/));

  urls = urls.concat(assetUrlsIn('sounds', /\.mp3$/));

  manifest = manifest.replace("{ASSET_URLS}", urls.join("\n"));

  fs.writeFile(fullPath('fowl.manifest'), manifest);

  console.log("Successfully wrote to fowl.manifest");

}).call(this);
